In [1]:
import pandas as pd

In [5]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [15]:
data={'Maths':91,
     'computer':90,
     'chemistry':92}
s=pd.Series(data)
print(s)

Maths        91
computer     90
chemistry    92
dtype: int64

In [19]:
s=pd.Series([10,20,30,40])
print(s[0])

10

In [21]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s['C'])

300

In [23]:
print(s[['A','B']])

A    100
B    200
dtype: int64

In [27]:
s=pd.Series([10,20,30,40])
print(s.size)
print(s.shape)
print(s.dtype)

4
(4,)
int64

In [31]:
s=pd.Series([10,20,30,40])
print(s+10)
print(s*2)

0    20
1    30
2    40
3    50
dtype: int64
0    20
1    40
2    60
3    80
dtype: int64

In [37]:
print("Sum=",s.sum())
print("Mean=",s.mean())
print("Maximum=",s.max())
print("Minimum=",s.min())

Sum= 100
Mean= 25.0
Maximum= 40
Minimum= 10

In [47]:
data={'RollNo':[6,7,4],
     'Name':['Apara','purvi','Bani'],
     'Marks':[92,90,98]
     }
df=pd.DataFrame(data)
print(df)

   RollNo   Name  Marks
0       6  Apara     92
1       7  purvi     90
2       4   Bani     98

In [49]:
df=pd.DataFrame(data,
               index=['A','B','c'])
print(df)

   RollNo   Name  Marks
A       6  Apara     92
B       7  purvi     90
c       4   Bani     98

In [24]:
import pandas as pd

In [26]:
data={'RollNo':[6,7,4],
     'Name':['Apara','purvi','Bani'],
     'Marks':[92,90,98]
     }
df=pd.DataFrame(data)
print(df)

   RollNo   Name  Marks
0       6  Apara     92
1       7  purvi     90
2       4   Bani     98

In [28]:
print(df.shape)
print(df.columns)

(3, 3)
Index(['RollNo', 'Name', 'Marks'], dtype='object')

In [30]:
print(df['Name'])

0    Apara
1    purvi
2     Bani
Name: Name, dtype: object

In [32]:
print(df.index)
print(df.dtypes)

RangeIndex(start=0, stop=3, step=1)
RollNo     int64
Name      object
Marks      int64
dtype: object

In [34]:
print(df[['Name','Marks']])

    Name  Marks
0  Apara     92
1  purvi     90
2   Bani     98

In [38]:
print(df.loc[0])
print(df.loc[2])

RollNo        6
Name      Apara
Marks        92
Name: 0, dtype: object
RollNo       4
Name      Bani
Marks       98
Name: 2, dtype: object

In [42]:
print(df.loc[[0,2]])

   RollNo   Name  Marks
0       6  Apara     92
2       4   Bani     98

In [44]:
print(df.iloc[1])

RollNo        7
Name      purvi
Marks        90
Name: 1, dtype: object

In [46]:
print(df.iloc[[0,2]])
print(df.iloc[0:2,1:3])

   RollNo   Name  Marks
0       6  Apara     92
2       4   Bani     98
    Name  Marks
0  Apara     92
1  purvi     90

In [87]:
data={'RollNo':[6,7,4],
     'Name':['Apara','purvi','Bani'],
     'Marks':[92,90,98]
     }
df=pd.DataFrame(data)
print(df)

   RollNo   Name  Marks
0       6  Apara     92
1       7  purvi     90
2       4   Bani     98

In [91]:
df['Marks']=df['Marks']+5
print(df)

   RollNo   Name  Marks
0       6  Apara    102
1       7  purvi    100
2       4   Bani    108

In [93]:
df['Grade']=['A','A+','B']
print(df)

   RollNo   Name  Marks Grade
0       6  Apara    102     A
1       7  purvi    100    A+
2       4   Bani    108     B

In [95]:
df.drop('Grade',axis=1,inplace=True)
print(df)

   RollNo   Name  Marks
0       6  Apara    102
1       7  purvi    100
2       4   Bani    108

In [97]:
print(df['Marks'].sum())

310

In [99]:
print(df['Marks'].mean())

103.33333333333333

In [101]:
print(df['Marks'].max())

108

In [103]:
print(df['Marks'].min())

100

In [105]:
df.sort_values('Marks')

   RollNo   Name  Marks
1       7  purvi    100
0       6  Apara    102
2       4   Bani    108

In [107]:
df.sort_values('Marks',ascending=False)

   RollNo   Name  Marks
2       4   Bani    108
0       6  Apara    102
1       7  purvi    100